import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { apiSrv, authSrv } from '../services';
import {
  LoginForm,
  RegisterForm,
  VerifyUser,
  TransferForm,
} from '../components';
import { AuthenticatedPage, DashboardPage } from '../layouts';
import { useContext } from 'react';
import { GlobalStatesContext } from '../contexts';

const Home: NextPage = () => {
  const handleTestApi = async () => {
    const data = await apiSrv.get({
      url: 'users',
    });
    console.log(data);
    alert('finish');
  };

  const handleLogout = () => {
    authSrv.deleteAuthInfo();
    location.reload();
  };

  const globalStates = useContext(GlobalStatesContext);

  return (
    <AuthenticatedPage>
      <DashboardPage options={[]}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta
              name="description"
              content="Generated by create next app"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <div>
              <h1>Currencies</h1>
              <div>{JSON.stringify(globalStates.currencies)}</div>
            </div>
            <div>
              <h1>test API</h1>
              <button onClick={handleTestApi}>Click Me</button>
            </div>
            <div>
              <h1>logout</h1>
              <button onClick={handleLogout}>logout</button>
            </div>
            <LoginForm />
            <RegisterForm />
            <VerifyUser />
            <TransferForm />
          </main>
        </div>
      </DashboardPage>
    </AuthenticatedPage>
  );
};

export default Home;
