import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './index.module.css';
import { AuthenticatedPage, DashboardPage } from '../layouts';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Labpro Selection App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthenticatedPage>
        <DashboardPage options={[]}>
          <div
            className={
              styles.container + ' d-flex p-5 align-items-center'
            }
          >
            <div className={styles.rightContainer}>
              <div className={styles.imgContainer}>
                <img src="/register-icon.svg" alt="" />
              </div>
            </div>
            <div className={styles.leftContainer}>
              <h1 className={styles.title + ' text-end'}>
                Welcome to the Labpro Selection App
              </h1>
            </div>
          </div>
        </DashboardPage>
      </AuthenticatedPage>
    </>
  );
};

export default Home;
